### ISSUE TITLE
Check the correctness of node/relation mappings if users provide such mappings.

### ISSUE THREAD

**Issue by zheng-da** [awslabs/dgl-ke#96]
DGL-KE needs to verify the mappings and report more informative errors if the input data fails the checks.

**Comment by AlexMRuch** [comment]
One thing I realized while using `dgl-ke` is that at one point my entity/relation maps both had extra information (nodes and relations that did not appear in my canonical tuples, the result of bad data filtering on my end) and this caused my embeddings to be many times larger than they were after I removed those entities/relations (because `dgl-ke` created embedding rows/cols for those entities/relations despite never updating them because it never saw them).

Having a check that would only create an embedding row/col for entities/relations if they appear in the canonical tuples (or at least a warning that extra information exists in the entity/relation maps) would be helpful to avoid such wasted memory.

**Comment by classicsong** [comment]
Add some basic checking of ID space (entity ID should >= 0 and < num_of_entities right now, same for relation ID).
For UDD, triplets should only contain integer IDs.
See PR #105
